name: mentor_coffee
description: Sample app

version: 1.0.0+1

environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  provider: ^4.3.2

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
